server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice #OrderService客户端名称
  cloud:
    nacos:
      server-addr: nacos:8848 #nacos服务地址
      discovery:
        cluster-name: HZ
 #       namespace: 5f9e8dea-1656-47d1-a174-0d7acbc38b70 #命名空间dev的id
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://localhost:8079/eureka
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      -userservice
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对httpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数